### ISSUE TITLE
No interior defence battles for Whiterun,Riften and Markarth

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#109]
I know this ties into the castle evacuation, but it just feels wrong, Solitude and Windhelm have interior defence, why not the other 3 major holds?

**Comment by schofida** [comment]
I know :(

So the interior city sieges for Whiterun, Riften and Markarth only are handled by a hidden quest called cwattackcity. I would basically have to write cwescapecity to do largely the same thing except rescuing the jarl instead of forcing him/her to surrender. Windhelm and Solitude are handled completely differently.

As I said before, cwescapecity is very barebones so getting that up and running will take a lot of work. I have it only my list of enhancements.

**Comment by LABWAZHERE** [comment]
So, what’s the likely hood of it actually being implemented? If it isn’t high then, we’ll just have to hope on full release someone will be crazy enough to add a patch for it
