### ISSUE TITLE
X Marks the Docs - Falkreath Completion Quirk

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#123]
Stole documents and fast traveled to the camp to turn them in.

First, I crashed to desktop. This didn't happen the second time, though, so I'm not sure if this mod caused the crash or something else.

Second, when I tried again, I did not crash but instantly completed the quest upon arriving at the camp. I got the message about the siege phase advancing, and I got experience (I'm using the Experience mod which gives experience for completing quests). This was all before actually talking to Galmar. When I did get near Galmar, then he gave me 1000 gold and thanked me. No actual conversation started, though, and I didn't have to speak with him; just getting near was enough.

**Comment by schofida** [comment]
Did you happen to have that Crash Logger SKSE plugin to see what may have caused the crash?

Besides the crash, the rest of the behavior is intentional. I don't know why Bethesda designed it that way but the dialogue to hand out the reward and also to advance the stage quest just happens by being next to Rikke/Galmar. Since that happens, I didn't CWMission09 (X Marks the Docs) to trip over these proximity dialogue things so I complete the quest once the player enters the camp. Waiting until you go up to the Field CO might trip up these other dialogues.

**Comment by Eve-Knight** [comment]
I did not. I do now, though.

**Comment by Eve-Knight** [comment]
Except it's not valid for the current version. So I do not have it installed.

**Comment by schofida** [comment]
Did the crash happen as soon as you grabbed the document or was it when you fast traveled back to the camp?

**Comment by Eve-Knight** [comment]
It was when I fast traveled. It was probably Torches Cast Shadows.

**Comment by LABWAZHERE** [comment]
on an unrelated note can i just say how hyped i am for the next update, final stand with actual generals and talking to co before Spanish inquisition, it is gonna be fun

**Comment by ds-nscorp** [comment]
Thanks! I have some other changes in the works and I wanted to at least some testing to make sure these changes are working. Real life work has been BRUTAL this week. I will hopefully have some time this weekend.

**Comment by schofida** [comment]
Closing issue. I tried a couple times and could not cause crash to occur
