### ISSUE TITLE
Wizard's Staff Equip Failure Message Grammar

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#124]
Tried to equip Wizard's Staff. Got message of:

You are not worthy

I'm guessing I need to have more progress in the Mages Guild quests or higher magic skills. Presuming this much works as intended, though, since it's phrased as a sentence, it should probably have a period on the end.

**Comment by schofida** [comment]
This is something carried over from the OG CWO. Grammatical issue will be fixed in the next release.

In regards to the requirements, they are a bit obtuse (but I think Appolodown wanted it that way). You must have all 5 magic skills of at least 50 or one magic skill above 90.

If you get over that threshold, let me know what you think (I never used it)
