### ISSUE TITLE
Denfend Fort missions seems not work well

### ISSUE THREAD

**Issue by cyx19961114** [schofida/CWORR#141]
Play as Imperial,after losing Battle of Whiterun.Then enter defense.

The first Skymish at X works well.Then I get the latter X location is under attack.

The letter told me defend a Fort,but actually after reading it,a defense city siege will be started instead.

If you still travel to the fort,the defensive fort quest will start,but no enemy attacker.

**Comment by LABWAZHERE** [comment]
Fort sieges are not working properly atm, at least in my experience, if you could get a pic of the mcm menu then schofida will be able to diagnose the issue

**Comment by ds-nscorp** [comment]
I have a fix in the works. Should be posting a new release later this afternoon:)

**Comment by schofida** [comment]
This is hopefully fixed in this latest release https://github.com/schofida/CWORR/releases/tag/v1.0.15a. Please give it a try. Note that you may unfortunately need to load a save prior to the fort siege starting (like maybe before or directly after the village siege). Do note that if you are using Serious Civil War Commanders, I updated that patch as well: https://github.com/schofida/CWORR/releases/tag/SCWOFC Closing this for now. Please open a new issue if you are still experiencing problems
