### ISSUE TITLE
Stormcloak camps not activated in Stormcloak controlled regions (imperials)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#143]
Stormcloak camps in Stormcloak controlled areas (imperial) are not active on boot up of mod ( i used tmm 1 to double check) thus making it impossible to get x marks the docs documents from the Stormcloak camps, i believe they toggle on for the last battle and defector collector missions

**Comment by schofida** [comment]
This is by design. So whenever a new campaign starts (Tullius says 'Go to our hidden camp in X') The Campaign script hides the camp of the enemy (cus its 'hidden'). And then when the missions start, we programmatically check to see if we want the document alias to be at the camp or at the HQ (its a 50/50 chance). If it is at the camp then we enable at the camp and show it on the map. Last Battel works this way as well.
