### ISSUE TITLE
Guards treat windmills/grain mills as trespass zones even before war has started.

### ISSUE THREAD

**Issue by Unknown-Zombie** [schofida/CWORR#152]
_This is just a rehash of the discussion from the Nexus comments thread, transplanted here for your convenience in tracking it, and so that I can get notified about updates and respond in a timely manner._

When I approach grain mills, such as those found at Pelagia Farm near Whiterun, any nearby guards will draw their weapons, accuse me of trespassing, and warn me to leave. If I do not vacate quickly, they attack.

I have not started the civil war, and I'm not wearing any "colors," just some dwarven armor. I have tried turning off the disguise mechanic, but the guards still become hostile when I approach a grain mill.

Using "Get CWO Unstuck" in the MCM gave a message saying there was nothing to fix.

![2ojyJb4](https://github.com/schofida/CWORR/assets/2162191/c8229f3d-ad44-45f1-a85c-baa122758a66)

If it helps, the guards were running an AI package called "CWPatrolAndGuardWhileHoldConested."

![yfpaBGp](https://github.com/schofida/CWORR/assets/2162191/d99e0317-3eed-4ed2-8fbc-086a88834084)

The guard is part of these factions:

![20230721224533_1](https://github.com/schofida/CWORR/assets/2162191/e9e8ce1f-53f6-4b16-8998-ecead4d43fa7)

The script logger didn't make any log files in my documents folder, which I'm guessing is because I haven't actually even started the civil war yet for your scripts to even be running.

I created a new profile in MO, deactivated _everything_ except for SKSE, USSEP, and CWO. Then I started a new game and used console to teleport outside of Whiterun so that I could get near a grain mill there. The guard near the grain mill accused me of trespassing in this test.

![20230721233625_1](https://github.com/schofida/CWORR/assets/2162191/788e7076-f774-4b52-bf3b-2338c1201a42)

Also, it's been years since I've done a Skyrim playthrough, and I was beginning to wonder if maybe this is a vanilla mechanic that I just forgot existed. So, I did a sanity check by doing the same test as above with _only_ SKSE active. The guard does not care that I'm near the mill when CWO is not running.

**Comment by ds-nscorp** [comment]
Thank you very much for consolidating the messages and moving this to GitHub ( I like it much better) I take it you updated to version 1.0.19 and are still having an issue. I have some free time this evening so I will run a few tests. Appreciate your patience with this!

**Comment by Unknown-Zombie** [comment]
Correct, this issue is still present in 1.0.19. The last two screenshots in the original post (of the guard's factions, and of the CWO-only test) were both taken after upgrading to 1.0.19.

**Comment by schofida** [comment]
Thanks again for reporting this issue and your patience. I found it! If you get a chance, can you give this release a try? https://github.com/schofida/CWORR/releases/tag/v1.0.20

So there is a ContestedHold variable on the overarching CW quest that was never set before but since I am now using the built in functionality to start campaigns at holds after the battle for Whiterun, this variable is set to track what hold is set to be contested by you or your opposing faction. I set it right off the bat to Whiterun since that siege is always first. I didn't see that variable inherently doing anything so I thought nothing of it.

Turns out it was. That interaction and several others happening all around Skyrim were apparently implemented by Bethesda but never finished. Once CWO sets this value to something, it kind of wakes these interactions up.

My fix is basically to not set that variable and let it get set naturally after the battle for Whiterun.

It was a pain to find but I'm glad I know of this now.

**Comment by Unknown-Zombie** [comment]
Nice! 1.0.20 does fix it.

It's interesting how much of this questline Bethesda had cut out before release.

I'm glad you got to figure it out and I'm happy that I could provide useful enough information for you to even find the problem... Lol
