### ISSUE TITLE
Last Stand of Solitude issues

### ISSUE THREAD

**Issue by schofida** [schofida/CWORR#19]
the Solitude defence battle (Last stand) will not start unless one of the far most barricades is broken, in addition to this if you lose
you actually fail reunification of skyrim which is normal however the cutsence in castle dour does not play and you can not move
![image](https://user-images.githubusercontent.com/14967936/226152250-5df1e3b2-0b3e-41d3-bb13-5c0fb789673c.png)
![image](https://user-images.githubusercontent.com/14967936/226152257-33d27fe0-25b4-4d95-9f0f-454fe8738630.png)

**Comment by schofida** [comment]
@LABWAZHERE

> the Solitude defense battle (Last stand) will not start unless one of the far most barricades is broken.

Thanks. I regrettably never had the time to test the defense of Solitude. I will take a look.

>  in addition to this if you lose you actually fail reunification of skyrim which is normal however the cutsence in castle dour does not play

This was planned by Apollodown but he was not able to get the scene to play and I couldn't either. I plan on trying to get that to work. But in the meantime, if you fail the Last Stand sieges, I kill the commander/field co off screen.

> and you can not move

But this is bad lol. I'll fix.

**Comment by LABWAZHERE** [comment]
ah i see that makes sense

**Comment by LABWAZHERE** [comment]
> figured it out, isn't a bug the stormcloaks are just coming from haafinger camp which is really far away but it may only have triggered cause i went towards it, but i doubt it

**Comment by LABWAZHERE** [comment]
> > and you can not move

this also applies to Windhelm last stand and this also happens (albeit temporarily) during the imperial Victory scene in Palace of the kings

**Comment by LABWAZHERE** [comment]
update: nvm the last stand of solitude battle will not start unless you go close to the stormcloaks, applies to markarth and riften too. also after losing solitude you can't leave solitude
![20230401141559_1](https://user-images.githubusercontent.com/128126252/229263221-c71b06fc-1ab7-4055-aba9-aa0a3505b32a.jpg)
![20230401141540_1](https://user-images.githubusercontent.com/128126252/229263230-fd65fdb6-603a-4bc7-8259-9559b32742c6.jpg)
the only room that was accessible was the blue palace and then the same glitch (not moving) still occurred
![20230401141704_1](https://user-images.githubusercontent.com/128126252/229263342-4a369f6e-dcff-4f96-a5eb-4fdd16a5aeeb.jpg)

i also noticed you fixed the glitch by preventing castle dour from being unlocked, the second floor still isn't. also ulfric and galmar are standing still in solitude and not moving, to add to this you have a dialogue option that says "now that we've defeated the imperials. i think you should edit it so it says "now that you have defeated."

castle dour also gets locked on successful defence battle

this is a fresh save with the new update btw

**Comment by schofida** [comment]
I will look at this soon. I am slow to set up this scenario to see what's going on but I will take a look.

**Comment by schofida** [comment]
I made a bunch of improvements to this (and fixes to a couple other things). I am going to hopefully test tonight and put this in front of you tomorrow.

**Comment by ds-nscorp** [comment]
So I just pushed release v1.0.3a which restores the intended losing the war final scene that the old CWO wanted to implement. So if you lose the exterior siege for Windhelm and Solitude, it will then start the city proper siege. From there it's just an all out war. You win if you kill enough troops. You lose only if you fall in battle. If you lose, it plays the finale where you watch your leader and CO get killed.

I did not test a bit of this however and I would be very surprised if this all works. But I wanted to get this in front of you because I know that you will be unavailable for a few days soon.

**Comment by LABWAZHERE** [comment]
Unfortunately you released it a bit late, I am already unavailable, but i will be home by the 12th so i'll have to test it then

EDIT: My laptop might be able to run skyrim, what i'll do is download it on my laptop with mo2 and just download script extender and a couple of other mods and ill make my way to the solitude battle on a new save

**Comment by LABWAZHERE** [comment]
> So I just pushed release v1.0.3a which restores the intended losing the war final scene that the old CWO wanted to implement. So if you lose the exterior siege for Windhelm and Solitude, it will then start the city proper siege. From there it's just an all out war. You win if you kill enough troops. You lose only if you fall in battle. If you lose, it plays the finale where you watch your leader and CO get killed.

I like this idea for all the defence battles of the major holds, it feels lacking to not have a final stand inside the hold before capitulation.

**Comment by LABWAZHERE** [comment]
> I did not test a bit of this however and I would be very surprised if this all works. But I wanted to get this in front of you because I know that you will be unavailable for a few days soon.

As of the time of writing this I will be home in about 8 hours. When I arrive home I shall test and give you my findings for the update

**Comment by ds-nscorp** [comment]
Hey, sorry for the late reply. Please hold off on testing. I was able to get to the defense of Solitude to test last night and it definitely does not work. However, I made some good progress on getting it to work and I should have it ready for testing sometime tonight/tomorrow.

**Comment by schofida** [comment]
As usual the devil is in the details. I got almost everything working but there are a few things that stand out that are just a pain to iron out. I think I got it fixed. I am compiling everything and will do another run-through tomorrow before uploading (I would do it now but its almost 1:20AM over here :(

**Comment by LABWAZHERE** [comment]
hopefully it works, also with regards to the mcm issues, is that gonna be hard to fix?

**Comment by schofida** [comment]
I finally got it on v1.0.6a! Please verify when you have a chance..... Man fixing this was a pain in the ass lol

**Comment by LABWAZHERE** [comment]
The first test run Galmar did not spawn in properly (I think this was triggered by Galmar being downed) causing a few awkward pauses in dialogue when Ulfric realised Galmar had abandoned him (he was looking at the floor throughout the cutscene when Galmars lines were meant to be said presumably sad at his best friends abandonment) then proceeding to 1 v 2 Tullius and Rikke for a long time (he kept getting knocked down) after he successfully managed to kill Rikke, Tullius died from cringe (he has heart issues, too much cringe is bad for his heart) after which Ulfric started muttering to himself about Elisif (I think he has a crush on her) he then just casually walks outside and gives his speech while mourning his and Galmars friendship at least that's why i think he was looking down (it was the first time I was testing this I was very confused and I may be exaggerating some details) Apart from all this insanity 

it works (on second test all was normal) although i kinda wish you had of made Ulfric kill Tullius rather than him just dying but that might just be an impossibility, another thing i think is a bit ify is that they don't walk up to Tullius and Rikke after saying secure the door.

On another note: i'll never let Ulfric win, even when Tullius is dead (This isn't a glitch i used a mod to make Ulfric and Galmar killable during his speech)
![20230416152045_1](https://user-images.githubusercontent.com/128126252/232272921-374c4b8f-f2b9-4db9-9fc7-83f0257defb1.jpg)

**Comment by schofida** [comment]
> Tullius died from cringe (he has heart issues, too much cringe is bad for his heart)

This is the funniest thing that I have read in a while.
I think that there may be a way to force the package for the commander to deliver the killing blow. I will give it a try

**Comment by LABWAZHERE** [comment]
okay i think Ulfric and Galmar need to be realigned to match the stormcloak version (Galmar and Ulfric walk from the top door) 
cause this isn't meant to happen
![20230428130803_1](https://user-images.githubusercontent.com/128126252/235045415-be057f8f-726d-4727-8846-5ff093b9e2ca.jpg)

other than that
i think Tulius should still say his last words and that whole interaction until they mention the dragonborn should still occur as it is a crucial piece of lore that should still occur:
Ulfric: "This is it for you. Any last words before I send you to Oblivion?"
Tullius: "You realize this is exactly what they wanted."
Galmar: "What who wanted?"
Tullius: "The Thalmor. They stirred up trouble here. Forced us to divert needed resources and throw away good soldiers quelling this rebellion."
Ulfric: "It's a little more than a rebellion, don't you think?"
Galmar: "Heh."
Tullius: "We aren't the bad guys you know."
Ulfric: "Maybe not, but you certainly aren't the good guys."
Tullius: "Perhaps you're right. But then what does that make you?"
Ulfric: "You just said it yourself."
Galmar: "It makes us right."
Tullius: "And if I surrender?"
Ulfric: "The Empire I remember never surrendered."
Galmar: "That Empire is dead. And so are you."
Tullius: "So be it."
Galmar: "Just kill him and let's be done with it already."
Ulfric: "Come, Galmar. Where's your sense of the dramatic moment?"
Galmar: "By the gods! If it's a good ending to some damn story you're after - perhaps the Dragonborn should be the one to do it." don't add that one 
Ulfric: "Good point."
other than that we have a party crasher

![20230428130750_1](https://user-images.githubusercontent.com/128126252/235045346-fe831f85-bea3-4276-982f-988d30827b45.jpg)
but that's all

**Comment by schofida** [comment]
Should be fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.14a

Your commander will not die of cringe (the enemy commander delivers the killing blow) and Tullius will deliver his ending lines. (Note: Ulfric won't, Tullius just kills him. That conversation has too much Dragonborn talk)
