### ISSUE TITLE
Question: spanish inqusition how does it work?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#30]
the ability for defence battles for non capital holds (out of nowhere the stormcloaks decide to invade falkreath) how do they work? and if possible could you make it more like ocw where you can lose holds and gain them at random? it just in my opinion makes the civil war feel more grand and longer than it is (in a good way).

**Comment by ds-nscorp** [comment]
I have not gotten a chance to test this yet unfortunately but in theory whenever leaving some select locations (I am not at my PC but I think a few key ones are Dragon's Reach, Understone Keep, and Mistveil Keep), there is a small chance that a city siege defense will start. This currently only works at Whiterun, Markarth and Riften and your side of course has to own that hold.

So in regards to randomly changing holds, while it makes sense since the world doesn't revolve around you, I personally play very slowly and I don't want to get penalized for that 😀 

So before I hijacked the CWCampaign quest (which is unused in Vanilla) Bethesda did have a timer that they scrapped that would cause the current running hold to randomly change hands if you didn't go talk to Tullius or Ulfric before the timer ran out. I might try to make that a configurable MCM option once I get everything else working.

**Comment by LABWAZHERE** [comment]
> I have not gotten a chance to test this yet unfortunately but in theory whenever leaving some select locations (I am not at my PC but I think a few key ones are Dragon's Reach, Understone Keep, and Mistveil Keep), there is a small chance that a city siege defense will start. This currently only works at Whiterun, Markarth and Riften and your side of course has to own that hold.

 I do not believe it occurs as i have it set to 100 and nothing happened.


> So in regards to randomly changing holds, while it makes sense since the world doesn't revolve around you, I personally play very slowly and I don't want to get penalized for that 😀

Fair enough, i like the massive long drawn out war because i love torturing Ulfric

> So before I hijacked the CWCampaign quest (which is unused in Vanilla) Bethesda did have a timer that they scrapped that would cause the current running hold to randomly change hands if you didn't go talk to Tullius or Ulfric before the timer ran out. I might try to make that a configurable MCM option once I get everything else working.

if you make it an optional requirement that may be best. the way that ocw handles hold progression like the fact you can choose to have it activate before or after the battle of Whiterun and holds don't change hands until after battle of Whiterun is probably the best way to handle it.

**Comment by schofida** [comment]
> I do not believe it occurs as i have it set to 100 and nothing happened.

This should work now with v1.0.6a. And it should work for all holds (with the exception of Solitude and Windhelm).

**Comment by LABWAZHERE** [comment]
> > I do not believe it occurs as i have it set to 100 and nothing happened.
> 
> This should work now with v1.0.6a. And it should work for all holds (with the exception of Solitude and Windhelm).

Still testing this but 

I do still hope that you add the configurable option that make defence missions happen anywhere at anytime to make it feel more like an actual war and the struggle that it should be. Making it an optional mcm setting is still a good idea once everything else is stable

again do not get me wrong, I love cwo and I still will love this mod if you do not do this.

**Comment by LABWAZHERE** [comment]
> This should work now with v1.0.6a. And it should work for all holds (with the exception of Solitude and Windhelm).

remind me how how it functions so i can get this tested properly, is it the holds in general or a specific place i need to go?

**Comment by ds-nscorp** [comment]
I don't remember off the top of my head but leaving the headquarters of a hold you already own should work e.g Dragonsreach or Mistviel Keep

**Comment by LABWAZHERE** [comment]
okay update it works however 100% isn't every time i leave Dragonsreach or Mistviel Keep  additionally i have only encounted it at Riften and Whiterun

**Comment by schofida** [comment]
https://github.com/schofida/CWORR/releases/tag/v1.0.14a

This should be fixed now. Spanish Inquisitions will occur now in both major and minor holds
