### ISSUE TITLE
Tulius missing from major battles

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#34]
for some reason in the recent update (seasons unending one)

tulius doesn’t appear during the siege of Markarth Whiterun and riften and does not do his speech properly during the windhelm battle (with the restored fighting to windhelm scene) also tulius doesn’t do his victory speech 

(but that may just be because I punched an enemy jarl in windhelm after ulfrics death)

**Comment by schofida** [comment]
> (but that may just be because I punched an enemy jarl in windhelm after ulfrics death)

This is probably the case at the final siege. The AI packages are really finicky.

I was not able to reproduce this issue at Windhelm. Tullius's speech before the battle went off just fine. Keep in mind that there is a 50% chance at Markarth and Riften of Tullius showing up. Otherwise its just Rikke and she does the pep-talk.

**Comment by LABWAZHERE** [comment]
Huh I didn’t know that, is that the same with the whiterun offence siege?
