### ISSUE TITLE
MCM - changing amount of quests you get, works however

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#39]
okay so the mcm works however it starts regain _ hold after completing 2 quests in addition to this one of those mission doesn't get issued (i set it to 5 and i only got 3) she told me to collect defectors and then a dialogue option called ... appeared and she didn't mention any quest

**Comment by schofida** [comment]
I will take a look. Unfortunately this value might not update on an already running campaign

**Comment by LABWAZHERE** [comment]
> I will take a look. Unfortunately this value might not update on an already running campaign

okay i will clarify, this is a new campaign this is fresh off of winning the battle of solitude, activated the 5 choices during the pale campaign then retook it and got orders to save Falkreath

i got these issues at Falkreath

additionally i have narrowed it down to 3 quests:
 sabotage (i dont think you can get that one in falkfreath) x final battle and fort siege are the possible candidates for the non activating quest or it could be that cow one but i don't know anything about that one.

or it could just not be giving me 5 quests

**Comment by schofida** [comment]
> or it could just not be giving me 5 quests

I think that its this

**Comment by LABWAZHERE** [comment]
> I think that its this


no i don't think it is. other holds are giving me 4 quests

**Comment by schofida** [comment]
Sorry I wasn't clear. So when a campaign starts (a campaign is basically a handful of missions finishing off with a siege), when speaking to the Field CO, you he/she will send you on up to 2 missions at a time. Each mission on completion will increase the phase by one. Once it reaches the Max Phase (either 3 or 5 or 1 if you just want to jump straight to the siege), then the siege starts. Once that siege is over, the campaign finishes and then you see the commander to start a new campaign.

I think what was happening is that I fixed the MCM but if you had an already running campaign, the max phases was not getting changed. I am fixing that so that adjusting the phase in the MCM will update an already running campaign.

Keep in mind, currently only a Skirmish or Fort siege happens on Defense.

> it could be that cow one but i don't know anything about that one.

This one is kind of an Easter Egg. It will only start on the Stormcloaks side and only if you are on the offence at either Whiterun or the Pale. It is CWMission08 on https://tcrf.net/The_Elder_Scrolls_V:_Skyrim/Civil_War If you win, you actually get the giant as an ally in the next major city siege.

**Comment by schofida** [comment]
Closing this issue. Verified that max phase is getting updated, even mid-campaign.
