### ISSUE TITLE
Morthal and Winterhold prevent progression

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#42]
![20230417105908_1](https://user-images.githubusercontent.com/128126252/232355369-187e6c39-9812-4960-a180-d06489fdbf09.jpg)
that's all he says now i can't get my new orders
![20230417110111_1](https://user-images.githubusercontent.com/128126252/232355374-4a66dab2-7152-479f-8e76-c44595ae9d59.jpg)
regain the rift has been there since beating falkreaths pre siege missions
would love to give a pic of the debugger but
![20230417110514_1](https://user-images.githubusercontent.com/128126252/232355399-42e7aaf9-e300-42b2-b61a-d2fc1e5945cc.jpg)
it won't load so i can't progress

there may be some issues with winterhold and morthal since they are the last holds before the capital and this could still be interfering when Tullius randomly gives you holds

**Comment by LABWAZHERE** [comment]
Update reloading an earlier save prior to taking winterhold fixed this. i still don't know what caused it

**Comment by LABWAZHERE** [comment]
UPDATE: also occurs with morthal

this happens when you talk to tullius 
![20230417124211_1](https://user-images.githubusercontent.com/128126252/232365884-77048c50-ba90-443f-bdc6-fe8764eb349a.jpg)
the game softlocks only way to get out of this is to restart game and the mcm menu also breaks again.


an additional note, i reloaded a prior save and this happened

![20230417125142_1](https://user-images.githubusercontent.com/128126252/232366485-e848549e-3018-4f80-8762-bab721f647ee.jpg)

he kept attacking us (note i am wearing daedric armour not whiterun which is a rival hold the person in the pic is a modded follower)

in addition to that the other ones seem to also attack me when i exit.

they didn't do this first time round

**Comment by LABWAZHERE** [comment]
note: reloading a save before the battle of morthal and winterhold solves this issue however why it occurs in the first place is what needs to be investigated

**Comment by schofida** [comment]
So this one is scary.

So not to get too technical, CWO is crashing. Some part of Skyrim's scripting engine is causing the CWCampaign (unused vanilla quest) to stall. This has happened to me twice. I know that one time it was because I entered bleedout and CWO tried to determine the outcome but at the same our side ran out of troops.

I put in a fix to prevent that from happening at the same time and I added yet another potential fix to https://github.com/schofida/CWORR/releases/tag/v1.0.7a. Unfortunately this is a sneaky bug because it happens once the siege quest finishes. So you might not know for a while until you try to do any more Civil War interaction (like talking to Tullius). A sure fire way to know that you have this bug is when you pull up the MCM and it doesn't load. I haven't seen this issue since for about a week but please let me know if you come across this issue again.

**Comment by schofida** [comment]
I will leave this up for a week but I have not been able to reproduce for some time. Let me know if you any issues getting the commander to move you to a new hold.
