### ISSUE TITLE
hadvar missing from major battles?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#46]
is my boy hadvar and that ralof guy supposed to 100% appear in major hold battles or is that only a percentage chance?

**Comment by LABWAZHERE** [comment]
additional note when hadvar does appear he isnt in the heavy armour he sports in the battle of whiterun

**Comment by schofida** [comment]
I created an experimental release https://github.com/schofida/CWORR/releases/tag/v1.0.7a

Can you give that a try (provided that the city siege boots up)?

**Comment by LABWAZHERE** [comment]
hadvar appears now however he still doesnt have the heavy armour

**Comment by LABWAZHERE** [comment]
update: hadvar does not appear in the riften or markarth outside sieges he only appears inside the palaces

**Comment by schofida** [comment]
I think that I may have this fixed as well. Pushing new release soon.

**Comment by LABWAZHERE** [comment]
Hadvar unconfirmed, ralof didn’t appear at Markarth siege

**Comment by ds-nscorp** [comment]
Interior or Exterior? Exterior still needs some work. Interior should work though.

**Comment by LABWAZHERE** [comment]
> Interior or Exterior? Exterior still needs some work. Interior should work though.

Wasn’t paying attention for the interior but definitely not there in exterior also Galmar was miss aligned isn’t the co meant to be in front of all the troops giving them a pep talk?
Galmar was just with the crowd giving the speech

**Comment by LABWAZHERE** [comment]
His functionality inside understone was also broken he wasn’t walking up to the jarl he was just walking into a wall

**Comment by LABWAZHERE** [comment]
> His functionality inside understone was also broken he wasn’t walking up to the jarl he was just walking into a wall

Ralofs I mean

**Comment by LABWAZHERE** [comment]
wait, isn't hadvar and ralof sometimes meant to join you in fort battles?

**Comment by LABWAZHERE** [comment]
nvm it is the rescue missions they join you in

**Comment by schofida** [comment]
This should hopefully be fixed now https://github.com/schofida/CWORR/releases/tag/v1.0.10a. So Skyrim has an always running CWAllies quest where it will keep track of allies added to the war (e.g. Ralof, Hadvar, the new disaffected soldiers, and the new Goldar the Giant if you can get that quest). Hadvar and Ralof are added at the beginning of the Civil War and are set to show up in the battles of Morthal, Markarth, Falkreath, Whiterun, Dawnstar Riften and Winterhold. But unfortunately Bethesda only added the marker positions for the allies in Whiterun Solitude and Windhelm???? So in vanilla, only Whiterun ever worked.

Sometimes, I would like to strangle whatever Marketing guy that thought it would be a good idea to release Skyrim in the state that it was on 11.11.11 :(

I will add this to the enhancement list because I would eventually like to add the allies to the minor cities along with the defense for Riften and Markarth. This will take a lot of work :(

**Comment by schofida** [comment]
Added https://trello.com/c/oFLYcnMT/43-add-cwallies-functionality-to-minor-capitals to track adding allies to Minor Capital Sieges
