### ISSUE TITLE
Battle of Markarth (Imperials) not working properly

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#48]
same situation as whiterun
![20230417144844_1](https://user-images.githubusercontent.com/128126252/232381770-a49d480c-4f38-475f-8156-74e98dd7fb69.jpg)
![20230417144849_1](https://user-images.githubusercontent.com/128126252/232381774-84f9f94c-339a-47b4-8352-51803029d8c5.jpg)
![20230417145118_1](https://user-images.githubusercontent.com/128126252/232381775-b093ee19-4092-46cc-9eff-9a695790fcef.jpg)
![20230417145436_1](https://user-images.githubusercontent.com/128126252/232381913-0b2c72c5-b444-4fb2-b724-b317016a3fc6.jpg)
using fix quest
![20230417151217_1](https://user-images.githubusercontent.com/128126252/232384350-27736aa7-03dc-43d2-919e-ea8cfb1cbb78.jpg)

important to note:
using the win running quest mcm option does nothing. at all
Get stage cw siege 60.00
quest running 0.00
get stage cw attack city 9999.00

here is mcm
![20230417145908_1](https://user-images.githubusercontent.com/128126252/232382652-8a1479b8-96be-4a68-b9f9-b0132d51e625.jpg)

on an unrelated note i love the fact that you have former guards fighting to take back their city
![20230417144238_1](https://user-images.githubusercontent.com/128126252/232382741-cb3f7d5a-398d-4c74-9822-318561ac167c.jpg)

Can you add this for imperial whiterun attack siege of whiterun?

**Comment by LABWAZHERE** [comment]
i will note that it is only Markarth and Whiterun that won't function at all and it is only Morthal and Winterhold that cause dialogue issues all others function fine. which is interesting as the battle for Riften goes off without a hitch and usually when it comes to Markarth and Riften it is a similar situation to Morthal and Winterhold but this time it isn't

**Comment by schofida** [comment]
I created an experimental release [v1.0.7a ](https://github.com/schofida/CWORR/releases/tag/v1.0.7a)

So the culprit is 100% cwattackcity not firing. This quest handles all of the internal city events up to and including the Jarl surrendering for Whiterun, Markarth, and Riften (Solitude and Windhelm have their own barrels of fun :) ). So in order for these quests to start, a quest will a lot of the time have reference aliases that are pointers to various things that the quest needs to function. Reference aliases are important because a lot of these aliases can be set up from a location standpoint. That is how we can have the same siege quest start for different cities and the siege will point to the correct things in the city.

However, unless a quest reference alias is flagged as optional and the engine is unable to fill that reference, then the quest does not start. So what I did is flag a few more aliases as optional for this quest. Keep in mind, that these reference aliases are usually not flagged as optional for a reason. The cwattackcity quest may start, but then the surrender scene may be hosed because the 'Jarl' reference alias was never filled.

**Comment by LABWAZHERE** [comment]
Whiterun surrender scene hosed, other than that it works

update: 2nd attempt it works however the surrender and changeover scene doesn't work properly cause they don't say their lines properly and stuff but it progresses
(does baller have any snarky remarks to say to Vignar when he regains control?)

update 2: Markarth works and so does the change over scene (at least i think it does i am going off of the subtitles cause the markarth one is so long due to the walk up that i started exploring the palace)

**Comment by schofida** [comment]
Hey, thanks for all of the things that you found. I will have to take tonight off as I am oncall for work today. But I will hopefully get a chance to answer some things soon.

In the meantime, if you don't mind, can you find the save where Whiterun attack city started but the scene did not work and enter the following in the console: sqv cwattackcity

This will unfortunately take a bit of digging. I am looking for something like the jarl alias being none or the fieldco being none. If you want, you can send me everything but that might be a lot of screenshots.

And unfortunately no, "Baller" doesn't have anything to say. There was nothing recorded since this could not happen in vanilla. That also applies to a couple of other issues you mentioned that I will try to get to tomorrow.

**Comment by LABWAZHERE** [comment]
> In the meantime, if you don't mind, can you find the save where Whiterun attack city started but the scene did not work and enter the following in the console: sqv cwattackcity

Luckily i save major issues like this 
![20230419121322_1](https://user-images.githubusercontent.com/128126252/232949008-2745663c-a82c-4486-a905-2d115f055b92.jpg)

**Comment by schofida** [comment]
I apologize for not being clear. I see the screenshot but this is only a handful of refs. CWAttackCity has A LOT more. You can press PgUp to see more. Can you send me the others? I am particularly looking for the REF 'Jarl' and REF 'CityFieldCOImperial' and 'CityFieldCOSons'. I don't need to see the CitizenXX Refs. There's a ton of them but don't impact the City battles.

**Comment by LABWAZHERE** [comment]
ah i see i didn't know you could move up the console

**Comment by LABWAZHERE** [comment]
![Uploading 20230423092921_1.jpg…]()

**Comment by LABWAZHERE** [comment]
![20230423092939_1](https://user-images.githubusercontent.com/128126252/233811833-c45fd73d-8873-4961-a055-407a01bc986a.jpg)
![20230423092950_1](https://user-images.githubusercontent.com/128126252/233811834-fa611152-2bbe-450e-ab74-14c400f327c0.jpg)
![20230423092951_1](https://user-images.githubusercontent.com/128126252/233811835-b8c2de31-2bbe-45ff-a17d-f581a012babd.jpg)
![20230423092953_1](https://user-images.githubusercontent.com/128126252/233811836-e36bc0ba-03d1-4a3c-bccc-2b0b22c35958.jpg)
![20230423092956_1](https://user-images.githubusercontent.com/128126252/233811837-414ab8ed-4332-4259-8331-065b51d1e425.jpg)
![20230423093001_1](https://user-images.githubusercontent.com/128126252/233811840-d2f8a2b9-808f-42b1-82c8-72001fdc03bb.jpg)
![20230423093004_1](https://user-images.githubusercontent.com/128126252/233811841-a4370652-8433-4bbc-a6ed-9cba5210aae8.jpg)
![20230423093009_1](https://user-images.githubusercontent.com/128126252/233811843-097d617c-6a86-4163-864a-7d1fb1eb84f8.jpg)
![20230423093017_1](https://user-images.githubusercontent.com/128126252/233811845-09fa94c6-36d7-4f1b-8b02-d85a31a6fa60.jpg)
![20230423093024_1](https://user-images.githubusercontent.com/128126252/233811846-cd3bb85e-ba7e-4202-8322-0a3dd3dcdfa0.jpg)
![20230423093027_1](https://user-images.githubusercontent.com/128126252/233811848-bea82600-0d38-412c-9de1-64810a4ca541.jpg)
![20230423093032_1](https://user-images.githubusercontent.com/128126252/233811849-d79bf6e4-5cc4-442e-a665-61c1b3f8c768.jpg)
![20230423093041_1](https://user-images.githubusercontent.com/128126252/233811851-e05854e4-dd1b-4df5-874a-d21ac46fe912.jpg)
![20230423093100_1](https://user-images.githubusercontent.com/128126252/233811852-aef38b4f-104e-4ffc-a19c-965ad13f3972.jpg)

**Comment by schofida** [comment]
Thanks for posting these. Unfortunately it still does not appear that CWAttackCity was even running (all of the refs were none which is not possible). I marked a few of the reference aliases as optional reducing the tendency of the quest to just not start.

What I will work on next is putting in a Safe guard to just succeed the quest in case the interior part fails to start which will just succeed the whole siege quest. It's not ideal but its better than just being stuck.

**Comment by schofida** [comment]
Added a safeguard to complete the siege if CWAttackCity (interior siege including Jarl surrendering) fails to start. https://github.com/schofida/CWORR/releases/tag/v1.0.14a
