### ISSUE TITLE
Riften missions not advancing

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#50]
it seems like with every patched bug 5 more pop up. rikke won't issue new quests after completing first quests in riften
![20230418131711_1](https://user-images.githubusercontent.com/128126252/232662301-45f045e5-4daf-4138-b59e-868b9c505165.jpg)
here is mcm
![20230418131938_1](https://user-images.githubusercontent.com/128126252/232662377-5cd6be4a-43ab-49b9-b2bc-86fd68352768.jpg)

for clarification it didn't say setting up new missions

**Comment by LABWAZHERE** [comment]
also when you force start a campaign it says setting up campaign in___ campaign is miss spelt in that message

**Comment by LABWAZHERE** [comment]
i think you should re add the force start siege debug option as a fallback if this kind of bug occurs

**Comment by LABWAZHERE** [comment]
update: using win this hold breaks the civil war quest and the mcm

**Comment by LABWAZHERE** [comment]
update update: unsure what caused this on second attempt it worked fine

**Comment by schofida** [comment]
So I will try to replicate this but you might have hit an interesting edge case. Thanks to the CWO Debugger screen shot you provided, I can tell that you had a surprise defense of the city. Since the Rikke dialogue didn't work at one point and works now, I am wondering if the defense siege was still running (or in the stopping state). So when a siege is stopping (which happens once you actually leave the hold where the siege took place), it runs this routine to update ownership of the whole hold and is doing a bunch of cleanup stuff. This can sometimes take 2-3 actual human minutes to complete (due to Skyrim's extremely inefficient scripting engine). Missions do not get kicked off again until you don't have any other missions or sieges running. So this could have been an issue with just having to wait a little while. I'll see if there is a way to better synergize with the Surprise defense quest.

**Comment by LABWAZHERE** [comment]
while i did get a defence mission for riften in this case it was offence this can be seen by the flags in the bottom corner and by the mcm. idk why it was on defence cause i didn't get a defence battle until after this

**Comment by ds-nscorp** [comment]
Sorry for responding to this so late but do you happen to remember if the defense was for Riften or some other hold? It should not have been for Riften since you don't control it yet. When the CWCampaign quest is 200, that means a Spanish Inquisition occurred.

**Comment by LABWAZHERE** [comment]
i do remember one for whiterun occuring at some point but i don't remember if it was in that specific save but if a spanish inquisition did occur or is occuring i'd be whiterun since i haven't experienced them in the minor holds and because both markarth and riften are stormcloak leaving whiterun as the only option

**Comment by schofida** [comment]
Should be fixed going forward in https://github.com/schofida/CWORR/releases/tag/v1.0.14a

This was definitely a weird interaction between Spanish Inquisiton and continuing the campaign.
