### ISSUE TITLE
Lumber Mill Sabotage Issues

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#59]
Got quest to sabotage Half-Moon Mill. The male vampire attacked me on sight along with an imperial soldier. The female vampire did not. Not sure what's intended there.

Next, I struggled to figure out how to sabotage the mill. Tried attacking and burning where the quest marker pointed to no avail. Eventually noticed the prompt for pulling down a log to cut was slightly different, so tried that but got a message about a log already being ready to cut (none was visible in the cutting groove). And then eventually figured out the lever to start the saw was how to complete the sabotage, which kind of worked. It advanced the quest just fine but still had some other issues:

The debris that appears to represent the sabotage looks very strange, especially the part that appears to be intended as a mound rising up from the ground but instead floats in midair.

The female vampire continued to try to use the mill as if nothing happened, pulling a log from the pile. The sound effect for a log falling into the groove also played.

**Comment by schofida** [comment]
Sigh... The lumber mills are easily the worst of the sabotage missions and leads me to believe why Skyrim abandoned them in the first place. Bethesda left me very little to work with restoring some of these missions and the lumber mills are undoubtedly the worst. I might just leave them the way they are for now and will see if someone who does graphics can come up with something better in regards to how to sabotage the mills can come up with a more responsive mesh for sabotaging and better rubble.

In regards to the vampires, I tested Half-moon mill but it was during the day and I was met with no resistance. I might run the cwpreparecity on the towns when the quest starts to send the regular townsfolk to their houses while the quest is underway.

**Comment by Eve-Knight** [comment]
I got this quest again from Galmar and he didn't actually have dialogue for it. He had a generic line about having his hands full ... then there was an awkward pause ... then he said "also" and the dialogue for the X Marks the Docs quest, which I also received.

**Comment by Eve-Knight** [comment]
Worse, the wreckage from the last time I sabotaged it was still there, so the quest made no sense and I had to awkwardly jump over it to get to the lever to "sabotage" it again. Plus, the other vampire attacked me this time, so now they're both dead ... more dead.

**Comment by LABWAZHERE** [comment]
> I got this quest again from Galmar and he didn't actually have dialogue for it. He had a generic line about having his hands full ... then there was an awkward pause ... then he said "also" and the dialogue for the X Marks the Docs quest, which I also received.

This also happens with Rikke with these quests she pauses

**Comment by schofida** [comment]
> I got this quest again from Galmar and he didn't actually have dialogue for it. He had a generic line about having his hands full ... then there was an awkward pause ... then he said "also" and the dialogue for the X Marks the Docs quest, which I also received.

I am not sure how this happened. I have not been able to reproduce this. Do note that I have made a bunch of changes to the quest dialogues so it might work now?

To get technical, I have restored the CWCampaignFieldCOMission1Hook and CWCampaignFieldCOMission2Hook which is driven by quests kicked off in the Story Manager by CWMissionNode and CWOMissionNode2. Once the quest starts, it kicks off a dialogue condition which allows the FieldCO to say something about the quest. The CWCampaignFieldCOMission2Hook has the 'Also' dialogue. If something prevents any quests from  CWMissionNode or CWMissionNode2 from starting, then you get the '...' so the FieldCO moves on to the next line.

> Worse, the wreckage from the last time I sabotaged it was still there, so the quest made no sense and I had to awkwardly jump over it to get to the lever to "sabotage" it again. Plus, the other vampire attacked me this time, so now they're both dead ... more dead.

So this I was able to reproduce (to get technical, I'm an idiot 👎 ). I have fixed with https://github.com/schofida/CWORR/releases/tag/v1.0.9a I also set the NPC's at the location to bugger off so you shouldn't get attacked by vampires anymore.
