### ISSUE TITLE
vignar greymane in jarls clothing after he loses whiterun

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#60]
![20230422165202_1](https://user-images.githubusercontent.com/128126252/233768044-d2c983bb-833c-489e-83bb-f102b82b5083.jpg)

after he loses whiterun he looks like that and not what he is supposed to look like, it is important to note that this does not occur while he is on the throne

this could be a compatibility issue with a mod i have but i doubt it as the only mod i have that would do this (conquest) isn't active and even then you'd have to personally ask them to change if you had conquest

whiterun is imperial btw

**Comment by schofida** [comment]
This is probably a Skyrim bug since once Vignar became Jarl of Whiterun you cannot take it back from him.

I have a quick question about your save. Did you have Conquest of Skyrim active and then disabled the Mod? If you did disable the mod mid-save, did you clean your save with Fallrim Tools or something like that? I peered at Conquest of Skyrim and it had a lot of scripts in it, (some conflicting with CWO).

**Comment by LABWAZHERE** [comment]
No fresh save without conquest period. i disabled conquest before this save but i did not clean the other saves that had conquest cause again idk how to do that

the thing that confuses me is that he doesn't have jarl clothes while he is on the throne

**Comment by ds-nscorp** [comment]
Great just checking 😀

**Comment by schofida** [comment]
This should be fixed going forward in https://github.com/schofida/CWORR/releases/tag/v1.0.11a Skyrim just sets all Jarls back to Balgruufs clothes. Thanks to SKSE. I can hold onto their outfits and put it back on once the siege is over
