### ISSUE TITLE
First Battle for Whiterun (imperials)/ Jarl Balgruuf doesn't do his victory speech

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#85]
Jarl Balgruuf doesn't do his victory speech

Some soldiers have the glitch
![20230428123532_1](https://user-images.githubusercontent.com/128126252/235041702-de38f1cd-cebe-4d5e-9844-9c0b4d1d5233.jpg)
he was standing there basically the entire battle

Rikke misaligned 
![20230428123245_1](https://user-images.githubusercontent.com/128126252/235041599-75f7bddc-995e-497e-8228-1960fd6512cb.jpg)

she is meant to be in the middle
and soliders are running into Whiterun instead of standing for Balgruufs speech
![20230428124321_1](https://user-images.githubusercontent.com/128126252/235041863-321240ae-7915-436c-990b-9c66790b0aae.jpg)

(there is meant to be more than 2 people there)

Additionally
This is what hadvar is meant to look like in the sieges
![20230428123254_1](https://user-images.githubusercontent.com/128126252/235041568-f2a17a56-3f8c-4682-8b72-dd8fb617b542.jpg)

this is a non traitor run so i wasn't aware of the Battle of Whiterun issues

**Comment by LABWAZHERE** [comment]
additionally
report to Balgruuf the Greater, misc objective doesn't appear also if you get this working there is sometimes a bug

the miscellaneous objective "Report to the Jarl of Whiterun" will be stuck in your journal with no way to complete it.

**Comment by schofida** [comment]
I will leave this open but this may be fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.10a. There are a handful of cut non-respawning defense soldiers that were never enabled in vanilla. These soldiers might have futzed with Balgruuf's speech.

**Comment by LABWAZHERE** [comment]
![20230429134758_1](https://user-images.githubusercontent.com/128126252/235282163-0cdfa105-5f37-44a1-ba61-8ea6f5ae9684.jpg)
![20230429134847_1](https://user-images.githubusercontent.com/128126252/235282164-6b1a719c-4b94-405a-819f-5afa8751dfa5.jpg)
Rikke is still not aligned she needs to be standing in the middle of that top part

**Comment by LABWAZHERE** [comment]
speech still isn't working

**Comment by LABWAZHERE** [comment]
EDIT FOUND THE ISSUE, BALGRUUF SLEEPS IN FOR SOME REASON i don't think that is meant to happen

basically he doesn't do it at night for some reason

**Comment by LABWAZHERE** [comment]
okay so a few things, one rikke didn't do speech, but i could have gone too close to her, 
additionally
![20230514101120_1](https://github.com/schofida/CWORR/assets/128126252/37ca9cc1-231c-4513-b8dc-39eec0e67a9b)
![20230514101134_1](https://github.com/schofida/CWORR/assets/128126252/6d41e99d-34a2-4cd7-ae6f-7bcba834b5e0)
balgruufs speech doesn't have irelith or proventus, and there is like no one there listening to his speech

**Comment by LABWAZHERE** [comment]
and rikke is offcentred and you still have to wait one hour for balgruufs speech rather than instant

**Comment by LABWAZHERE** [comment]
update: rikke does speech i was just too close to her

**Comment by LABWAZHERE** [comment]
update update: This occured upon reload:
![20230514102109_1](https://github.com/schofida/CWORR/assets/128126252/be52580c-af81-4b8f-910e-5b2815583e0f)
i waited like 3 hours and nothing

**Comment by schofida** [comment]
For the record: This Balgruuf speech is the bane of my g*d-damn existence.

**Comment by LABWAZHERE** [comment]
fair

**Comment by JohnMilsim** [comment]
Not sure if I am posting this correctly so forgive me, but after his speech he will be indefinitely "busy" until you fast travel away from Whiterun and fast travel back. 

It's not that much a problem and I'm not sure if its due to one of my other mods causing it (I have none that also edit the civil war) but I noticed that this wasn't a problem in the nexus version as I was able to talk to him soon as the speech ended to get my reward, however in this version he's forever "busy" until you unload Whiterun and reload it by fast travelling.

**Comment by LABWAZHERE** [comment]
what mods do you have that may effect balgruuf?

**Comment by JohnMilsim** [comment]
Far as I know, none. 

If it helps I'm using the Dragonborn wabbajack modlist, and I know there might be some way by using Mod Organizer to see what mod edits files and overwrites it, but I don't know it off the top of my head. I skimmed through the list of mods on Mod Organizer, and it looks like none of them mess with Balgruuf at all. And a quick check ingame with some better console UI mod shows that Balgruuf was last changed by the Unofficial Skyrim Patch. 

Like I said, it's not that big of a deal, I figured it might've been better to post my fix of it in case others were having the same problem I was.

**Comment by JohnMilsim** [comment]
I forgot also mention that Balgruuf actually got stuck on the barricades that spawn in the interior of Whiterun. I had to go through the gates and destroy all of them so Balgruuf can pathfind his way outside to give his speech.

**Comment by LABWAZHERE** [comment]
did you make balfgruuf swap sides? (balgruuf dilemma is built into this mod) that could be an issue

**Comment by JohnMilsim** [comment]
I didn't even know you could do that. No, I'm playing an imperial playthrough. If the balgruuf dilemma wasn't built into the nexus version that I can see why it might've bugged with this version. But on both playthroughs of the different versions on the mod I was on the imperial side.

**Comment by LABWAZHERE** [comment]
Wait, did you make a new save when going from Nexus to GitHub?, If not that is the issue. Especially with this speech the amount of changes Schofida has made.

**Comment by JohnMilsim** [comment]
I figured you would've asked that, but yes. I made sure to start a new save once I installed the github version.

But I should mention that I attempted to try to play the github version on the same save as the nexus version on an old save before I noticed the obvious issues it was causing so I deleted the save, wiped the nexus edition completely off my game, and then restarted my game and created a new save. (Since from I learnt years ago from playing Bethesda games that sometimes things can "carry over" throughout saves)

**Comment by LABWAZHERE** [comment]
You may have to wipe all saves then reinstall and uninstall or use a save cleaner, that or this is in the GitHub version, personally i have never encountered that issue as i usually just wait outside for him to teleport there (like use the wait feature)

**Comment by LABWAZHERE** [comment]
also @schofida here is how it goes in vanilla:
https://www.youtube.com/watch?v=vsTYq9DE58g
(6:31 is the speech)

Additionally Rikke isn't misaligned according to vanilla

**Comment by JohnMilsim** [comment]
That is pretty much what I've did, minus using a save cleaner.

I think you forgot that I mentioned that it wasn't that much a problem, since all I had to do was unload Whiterun by fast travelling and reload it by going back. Jarl Balgruuf was no longer busy and I was able to collect my reward.

He also did get stuck on the interior barricades when he tried to run down to give his speech, but last I checked this was always a problem for me even without a civil war mod, so I was used to destroying the interior barricades, running back outside to his speech spot, and waiting a few ingame hours.

**Comment by LABWAZHERE** [comment]
>It's not that much a problem and I'm not sure if its due to one of my other mods causing it (I have none that also edit the civil war) but I noticed that this wasn't a problem in the nexus version as I was able to talk to him soon as the speech ended to get my reward, however in this version he's forever "busy" until you unload Whiterun and reload it by fast travelling.


Still though that is what concerns me, some difference has made the GitHub version not function properly, Schofida is better equip to answer this question as i know little as to how the mod actually functions, that 

or this is actually vanilla behaviour (i haven't played vanilla for a long time)

**Comment by JohnMilsim** [comment]
> or this is actually vanilla behaviour (i haven't played vanilla for a long time)

I don't usually play the civil war questline in my playthroughs. (because I hate how Whiterun is trashed after) But the part of balgruuf getting stuck on the barricades has happened only a few times, twice in a vanilla civil war playthrough, and once on the github version. 

The part of him being busy until you unload Whiterun and reload it is new however.

**Comment by LABWAZHERE** [comment]
>(because I hate how Whiterun is trashed after)

ATCWR is a good mod then after the war it allows you to repair the cities, wouldn't recommend using it with CWORR just yet though because while it works, Last Stand battles trigger it, a patch for it is in the to do list though

**Comment by schofida** [comment]
Looking into this now
