### ISSUE TITLE
Regain rift started by completing rescue mission at Fort Kastav

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#94]
![20230428215712_1](https://user-images.githubusercontent.com/128126252/235268053-ef6e4d50-6f73-40f2-adcf-a56c8481ecea.jpg)
![20230429090904_1](https://user-images.githubusercontent.com/128126252/235268065-d5af12bf-6b7d-46b7-90ab-5142a29f9994.jpg)

**Comment by LABWAZHERE** [comment]
it isn't the same map marker like it was before but like it shouldn't activate until after winterhold is captured

**Comment by ds-nscorp** [comment]
This is borked. I wouldn't continue. This should not have happened at all.

**Comment by LABWAZHERE** [comment]
everything else worked fine until eastmarch cause i didn't get battle for fort amol

speaking of which

Legate Rikke doesn't have reporting for duty after regaining Rift in this save

**Comment by schofida** [comment]
I could not reproduce. You might need to check for conflicts particularly script file QF_CWMission04_00035A23. In vanilla completing CWMission04 (Rescue from X) had a routine that would win you the entire hold (which is strange and inconsistent with the other quests but since Vanilla skyrim did not car, I guess its ok). But this really messes with CWO.
